# Generated by Django 3.1.5 on 2021-01-19 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtor',
            old_name='desription',
            new_name='description',
        ),
    ]
